[project]
name = "business-rules"
version = "1.5.2"
description = "Python DSL for setting up business intelligence rules that can be configured without code"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytz>=2025.2",
    "six>=1.17.0",
]
