# This workflow will create venv, install requirements & run nosetests.
# The purpose is to run unit tests automatically when we push a remote branch to business-rule repo

name: unit-tests

# Controls when the workflow will run
#Triggers the workflow on push or pull request events but only for the master branch

on: [push]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          
    # Installing all dependencies
      - name: Install the project
        run: |
          uv sync --all-extras --dev
      
    # running the tests
      - name: Running Tests
        run: |
          uv run nose2
